export const initialState = {
  brands: {
    status: 'idle',
    isInLocalStorage: false,
    key: 'brands',
    length: 0,
  },
  cities: {
    status: 'idle',
    isInLocalStorage: false,
    key: 'cities',
    length: 0,
  },
  color_schemas: {
    status: 'idle',
    isInLocalStorage: false,
    key: 'colorSchemas',
    length: 0,
  },
  companies: {
    status: 'idle',
    isInLocalStorage: false,
    key: 'companies',
    length: 0,
  },
  countries: {
    status: 'idle',
    isInLocalStorage: false,
    key: 'countrues',
    length: 0,
  },
  currency: {
    status: 'idle',
    isInLocalStorage: false,
    key: 'currency',
    length: 0,
  },
  exchange_rates: {
    status: 'idle',
    isInLocalStorage: false,
    key: 'exchangeRates',
    length: 0,
  },
  family_statuses: {
    status: 'idle',
    isInLocalStorage: false,
    key: 'familyStatuses',
    length: 0,
  },
  genders: {
    status: 'idle',
    isInLocalStorage: false,
    key: 'genders',
    length: 0,
  },
  languages: {
    status: 'idle',
    isInLocalStorage: false,
    key: 'languages',
    length: 0,
  },
  measure_units: {
    status: 'idle',
    isInLocalStorage: false,
    key: 'measureUnits',
    length: 0,
  },
  packing_materials: {
    status: 'idle',
    isInLocalStorage: false,
    key: 'packingMaterials',
    length: 0,
  },
  payment_types: {
    status: 'idle',
    isInLocalStorage: false,
    key: 'paymentTypes',
    length: 0,
  },
};
